version: "3.9"

services: 
  database_rentx:
    image: postgres
    container_name: database_rentx
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres
    network_mode: host

  app:
    build: .
    container_name: rentx
    ports:
      - 3333:3333
      - 9229:9229
    volumes:
      - .:/usr/ap
    links: 
      - database
    depends_on:
      - database
    

volumes: 
  pgdata:
    driver: local